### ISSUE TITLE
Follow PEP8 conventions when writing code.

### ISSUE THREAD

**Issue by ZetaHunter** [Arcbot-Org/Arcbot-Core#33]
Per the title I'd like to suggest we follow PEP8 guideline.
Right now a lot of code fails to go thru PEP8 validation. (PyCharm has builtin pep8 validator)

**Comment by ph7vc** [comment]
I've followed PEP8 pretty closely with 2 exceptions:
- I don't use snake_case, it takes me a longer to type and copy and paste is annoying with my editor; so variable names I prefer to use camelCase; personally I think it makes code easier to read, and I can quickly identify special methods or attributes because underscores stick out in my code
- Module names are uppercase, that wasn't really a preference, just happend to do it that way since I used to be a Java programmer.

I don't really believe in strictly adhering to a code standard; all I care about is having readable code and honoring popular Python conventions.

**Comment by ZetaHunter** [comment]
Well there are still some little things like extra whitespace, ( ) in conditionals which shouldn't be there.

**Comment by ph7vc** [comment]
Well again like I said; there might be a few deviations from PEP8, which is fine with me, im not going to scrutinize my code to that extent. All I care about is that I can read it in the future and understand what is going on without having to do a bunch of digging

**Comment by ZetaHunter** [comment]
Would it be okay if I go around the code with PyCharm and clean it up? (add extra whitespaces, etc)
